#!/bin/bash

while IFS="" read -r; do
    echo "$REPLY"

    if test "$REPLY" = "//wasm_embedded_base64"; then
        echo -n "const wasm_embedded_base64 = \"\"";

        base64 showcqt.wasm | while IFS="" read -r; do
            echo " +"
            echo -n "\"$REPLY\""
        done
        echo ";"
    fi

    if test "$REPLY" = "//wasm_simd_embedded_base64"; then
        echo -n "const wasm_simd_embedded_base64 = \"\"";

        base64 showcqt-simd.wasm | while IFS="" read -r; do
            echo " +"
            echo -n "\"$REPLY\""
        done
        echo ";"
    fi

done < showcqt-template.js > showcqt.js
