/*
 * Copyright (c) 2020 Muhammad Faiz <mfcc64@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

/* Audio visualization based on showcqt mpv/ffmpeg audio visualization */
/* See https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/avf_showcqt.c */
/* The output frequency range is fixed between E0 - 50 cents and E10 - 50 cents. */

/*
 * Example usage:
 *
 * // Instantiate transform context. The context is uninitialized.
 * var cqt = await ShowCQT.instantiate();
 *
 * // Initialize transform context. May be called multiple times (reinitialization).
 * // Constraints:
 * //     0 < rate <= 96000 (actually slightly above 96000)
 * //     0 < width <= 7680
 * //     0 < height <= 4320
 * //     1.0 <= bar_v (bar height) <= 100.0
 * //     1.0 <= sono_v (brightness) <= 100.0
 * //     If supersampling is true, the actual transform will be twice the width.
 * var rate = audio_ctx.sampleRate;
 * var width = canvas.width;
 * var height = canvas.height;
 * var bar_v = 15;
 * var sono_v = 25;
 * cqt.init(rate, width, height, bar_v, sono_v, supersampling);
 *
 * // Change height at runtime.
 * height = 256;
 * cqt.set_height(height);
 *
 * // Change volume (bar height and brigthness) at runtime.
 * bar_v = 10;
 * sono_v = 20;
 * cqt.set_volume(bar_v, sono_v);
 *
 * // Set analyser fft size.
 * analyser_left.fftSize = cqt.fft_size;
 * analyser_right.fftSize = cqt.fft_size;
 *
 * function draw() {
 *     // Set input time domain data.
 *     analyser_left.getFloatTimeDomainData(cqt.inputs[0]);
 *     analyser_right.getFloatTimeDomainData(cqt.inputs[1]);
 *     cqt.calc();
 *     for (let y = 0; y < height; y++) {
 *         // Render line, result is in cqt.output.
 *         // equal to cqt.render_line_opaque(y)
 *         cqt.render_line_alpha(y, 255);
 *         canvas_buffer.data.set(cqt.output, 4*width*y);
 *     }
 *     requestAnimationFrame(draw);
 * }
 * requestAnimationFrame(draw);
 *
 */

{
//wasm_embedded_base64
const wasm_embedded_base64 = "" +
"AGFzbQEAAAABKghgAXwBfGABfwF/YAABf2AGf39/fX1/AX9gAABgAX8AYAJ/fwBgAn19AAIpBANl" +
"bnYDbG9nAAADZW52A2NvcwAAA2VudgNzaW4AAANlbnYDZXhwAAADFBMBAgMEBQUFBQYFBwUFBQUF" +
"BQUFBAUBcAEBAQUDAQB2BgkBfwFBoLjUAwsHgAEJBm1lbW9yeQIAD2dldF9pbnB1dF9hcnJheQAE" +
"EGdldF9vdXRwdXRfYXJyYXkABQRpbml0AAYEY2FsYwAHEXJlbmRlcl9saW5lX2FscGhhAAwScmVu" +
"ZGVyX2xpbmVfb3BhcXVlAA0Kc2V0X3ZvbHVtZQAOCnNldF9oZWlnaHQADwqBZRMRACAAQQBHQRF0" +
"QYCIgIAAagsIAEGAiJCAAAvZDQQBfwJ8A38JfEEAIQYCQCABQX9qQf87Sw0AIAJBf2pB3yFLDQBB" +
"ACEGQQAgAjYChLjQgwBBACABNgKAuNCDAEEAQwAAyEIgA0MAAIA/IANDAACAP14bIANDAADIQl4b" +
"OAKYuNCDAEEAQwAAyEIgBEMAAIA/IARDAACAP14bIARDAADIQl4bOAKUuNCDACAAQcBBakHgzgVL" +
"DQACQAJAIAC3IgdEH4XrUbge1T+iEICAgIAARO85+v5CLuY/o5siCJlEAAAAAAAA4EFjRQ0AIAiq" +
"IQEMAQtBgICAgHghAQsgAUF2akEKSw0AQQAhBkEAQQEgAXQiCTYCiLjQgwAgCUGAgAJKDQBBIiAB" +
"ayEAQQEgAUF+aiIGdCEKQX8gBnRB//8DcyELQQAhAUGA8CUhBgNAIAZBgIiAgABqIAZBgJBaakGq" +
"1arVenEgAUEBdkHVqtWqAXFyIgJBAnRBzJmz5nxxIAJBAnZBs+bMmQJxciICQQR0QfDhw4d/cSAC" +
"QQR2QY+evPAAcXIiAkEIdEGA/oN4cSACQQh2Qf+B+AdxckEQdyAAdiALcTsBACAGQQJqIQYgAUEB" +
"aiIBIApIDQALAkAgCUEDSA0AQQIhAANAAkAgAEUNACAAQQF2IQFEGC1EVPshGUAgALciDKMhDSAA" +
"QQN0QYT4kYAAaiEGQQAhAkQAAAAAAAAAACEIA0AgBkF8aiANIAiiIg4QgYCAgAC2OAIAIAYgDhCC" +
"gICAALaMOAIAIAZBCGohBiAIRAAAAAAAAPA/oCEIIAJBAWoiAiABSQ0AC0TSITN/fNkiQCAMoyEN" +
"IAAgAWpBA3RBhPiRgABqIQZBACECRAAAAAAAAAAAIQgDQCAGQXxqIA0gCKIiDhCBgICAALY4AgAg" +
"BiAOEIKAgIAAtow4AgAgBkEIaiEGIAhEAAAAAAAA8D+gIQggAkEBaiICIAFJDQALCyAAQQF0IgAg" +
"CUgNAAsgCUEEbSEBIAlBBEgNAEQYLURU+yEZQCAJt6MhDSAJQQN0QYT4kYAAaiEGRAAAAAAAAAAA" +
"IQgDQCAGQXxqIA0gCKIiDhCBgICAALY4AgAgBiAOEIKAgIAAtow4AgAgBkEIaiEGIAhEAAAAAAAA" +
"8D+gIQggAUF/aiIBDQALCwJAAkAgB0RMN4lBYOWgP6IiD5siCJlEAAAAAAAA4EFjRQ0AIAiqIQEM" +
"AQtBgICAgHghAQtBACABNgKQuNCDAAJAIAFBAUgNAEQAAAAAAAAAACEOQYD4poAAIQYDQCAORBgt" +
"RFT7IQlAoiAPoyIIIAigEIGAgIAAIQ0gCBCBgICAACEMIAYgCEQAAAAAAAAIQKIQgYCAgABE3uhj" +
"PiDQiT+iIAxEueAM/n4x3z+iRCqnPSXnxNY/oCANRKuxhLUxdsI/oqCgtjgCACAGQQRqIQYgDkQA" +
"AAAAAADwP6AhDiABQX9qIgENAAsLQQBBACgCgLjQgwBBAkEBIAUbbCILNgKMuNCDAAJAIAtBAUgN" +
"ACAHRAAAAAAAAOA/oiEQRAAAAAAAAPA/IAu3oyERQQAhCkQAAAAAAADwP0EAKAKIuNCDALciEqMh" +
"EyASRAAAAAAAACBAoiEUQQAhAQNAAkACQCARIAq3RAAAAAAAAOA/oERqyLi+07kbQKKiRBtu1ZvR" +
"+AdAoBCDgICAACIIIBBmQQFzDQAgCkEDdEGA+MiAAGpCADcDAAwBCwJAAkAgCCASoiAHoyIMIBRE" +
"rkfhehSuX0AgCEQfhetRuB7VP6IiCESPwvUoXI/qP6NEpaWlpaWloUCgo0SuR+F6FK5fQCAIRMP1" +
"KFyPwsU/o0SLgRLeaOp8QKCjoCAHoqMiDUQAAAAAAADgP6IiCKGbIg6ZRAAAAAAAAOBBY0UNACAO" +
"qiEGDAELQYCAgIB4IQYLAkACQCAMIAignCIImUQAAAAAAADgQWNFDQAgCKohAAwBC0GAgICAeCEA" +
"CwJAIAAgBmtBAWoiAiABaiIJQZj43wBMDQBBAA8LIApBA3QiBUGE+MiAAGogBjYCACAFQYD4yIAA" +
"aiACNgIAAkAgACAGSA0ARAAAAAAAAPA/IA2jIQ8gAUECdEGAuNCAAGohAQNAIA8gBrcgDKFEGC1E" +
"VPshGUCioiIIIAigEIGAgIAAIQ4gCBCBgICAACENIAEgE0F/QQEgBkEBcRu3oiAIRAAAAAAAAAhA" +
"ohCBgICAAETe6GM+INCJP6IgDUS54Az+fjHfP6JEKqc9JefE1j+gIA5Eq7GEtTF2wj+ioKCitjgC" +
"ACABQQRqIQEgBiAASCECIAZBAWohBiACDQALCyAJIQELIApBAWoiCiALRw0ACwtBACgCiLjQgwAh" +
"BgsgBgvRFgIOfxN9QQAoAoi40IMAIgBBAnUhASAAQQF1IQJBACgCkLjQgwAiAyEEAkAgA0EBSA0A" +
"IAJBA3QgA0ECdCIFayEGIAJBAnQgBWshByACIAFqIANrQQJ0IQhBgPilgAAhCUGAiICAACEFQQAh" +
"CgNAIAUgB2oiCygCACEMIAkuAQBBBXQiBEGEgKiAAGogC0GAgAhqKAIANgIAIARBgICogABqIAw2" +
"AgAgBEEIciILQYCAqIAAaiAFQYDwJmoiDCoCACAFIAZqIg0qAgCUOAIAIAtBhICogABqIAwqAgAg" +
"DUGAgAhqKgIAlDgCACAFIAhqIgtBgIAIaigCACEMIARBEHIiDUGAgKiAAGogCygCADYCACANQYSA" +
"qIAAaiAMNgIAIARBGHJBgICogABqQgA3AwAgBUEEaiEFIAlBAmohCSAKQQFqIgpBACgCkLjQgwAi" +
"BEgNAAsLAkAgBCABTg0AIAEgBGshCyAEQQF0QYD4pYAAaiEKIAQgAmoiBSADa0ECdEGAiICAAGoh" +
"BCAFIAFqIANrQQJ0QYCIgIAAaiEJA0AgBCgCACEMIAouAQBBBXQiBUGEgKiAAGogBEGAgAhqKAIA" +
"NgIAIAVBgICogABqIAw2AgAgBUEIckGAgKiAAGpCADcDACAJKAIAIQwgBUEQciINQYSAqIAAaiAJ" +
"QYCACGooAgA2AgAgDUGAgKiAAGogDDYCACAFQRhyQYCAqIAAakIANwMAIApBAmohCiAJQQRqIQkg" +
"BEEEaiEEIAtBf2oiCw0AC0EAKAKIuNCDACEACwJAAkACQAJAAkACQCAAQf8/Sg0AIABBgAhGDQEg" +
"AEGAEEYNAiAAQYAgRw0FQYCAqIAAEIiAgIAADAULIABBgMAARg0CIABBgIABRg0DIABBgIACRw0E" +
"QYCAqIAAEImAgIAAQYCArIAAEImAgIAAQYCAsIAAEImAgIAAQYCAtIAAEImAgIAAQQAhBUEAKgKE" +
"gLSAACEOQQBBACoChICogAAiD0EAKgKEgKyAACIQkyIRQQAqAoCAsIAAIhJBACoCgIC0gAAiE5Mi" +
"FJI4AoSAtIAAQQBBACoCgICogAAiFUEAKgKAgKyAACIWkyIXQQAqAoSAsIAAIhggDpMiGZM4AoCA" +
"tIAAQQAgDyAQkiIPIBggDpIiDpM4AoSAsIAAQQAgFSAWkiIQIBIgE5IiEpM4AoCAsIAAQQAgESAU" +
"kzgChICsgABBACAXIBmSOAKAgKyAAEEAIA8gDpI4AoSAqIAAQQAgECASkjgCgICogAADQCAFQYyA" +
"tIAAaiIEIAVBjICogABqIgkqAgAiDiAFQYiArIAAaiIKKgIAIg8gBUGM+JmAAGoqAgAiEJQgBUGI" +
"+JmAAGoqAgAiESAFQYyArIAAaiILKgIAIhKUkiITkyIUIAVBiPihgABqKgIAIhUgBUGIgLCAAGoi" +
"DCoCACIWlCAFQYz4oYAAaioCACIXIAVBjICwgABqIg0qAgAiGJSTIhkgBUGI+J2AAGoqAgAiGiAF" +
"QYiAtIAAaiIGKgIAIhuUIAVBjPidgABqKgIAIhwgBCoCACIdlJMiHpMiH5I4AgAgBiAFQYiAqIAA" +
"aiIEKgIAIiAgESAPlCAQIBKUkyIPkyIQIBYgF5QgFSAYlJIiESAbIByUIBogHZSSIhKTIhWTOAIA" +
"IA0gDiATkiIOIBEgEpIiEZM4AgAgDCAgIA+SIg8gGSAekiISkzgCACALIBQgH5M4AgAgCiAQIBWS" +
"OAIAIAkgDiARkjgCACAEIA8gEpI4AgAgBUEIaiIFQfj/A0cNAAwFCwtBgICogAAQioCAgAAMAwtB" +
"gICogAAQi4CAgAAMAgtBgICogAAQiYCAgAAMAQtBgICogAAQiICAgABBgICqgAAQiICAgABBgICs" +
"gAAQiICAgABBgICugAAQiICAgABBACEFQQAqAoSAroAAIQ5BAEEAKgKEgKiAACIPQQAqAoSAqoAA" +
"IhCTIhFBACoCgICsgAAiEkEAKgKAgK6AACITkyIUkjgChICugABBAEEAKgKAgKiAACIVQQAqAoCA" +
"qoAAIhaTIhdBACoChICsgAAiGCAOkyIZkzgCgICugABBACAPIBCSIg8gGCAOkiIOkzgChICsgABB" +
"ACAVIBaSIhAgEiATkiISkzgCgICsgABBACARIBSTOAKEgKqAAEEAIBcgGZI4AoCAqoAAQQAgDyAO" +
"kjgChICogABBACAQIBKSOAKAgKiAAANAIAVBjICugABqIgQgBUGMgKiAAGoiCSoCACIOIAVBiICq" +
"gABqIgoqAgAiDyAFQYz4lYAAaioCACIQlCAFQYj4lYAAaioCACIRIAVBjICqgABqIgsqAgAiEpSS" +
"IhOTIhQgBUGI+JmAAGoqAgAiFSAFQYiArIAAaiIMKgIAIhaUIAVBjPiZgABqKgIAIhcgBUGMgKyA" +
"AGoiDSoCACIYlJMiGSAFQYj4l4AAaioCACIaIAVBiICugABqIgYqAgAiG5QgBUGM+JeAAGoqAgAi" +
"HCAEKgIAIh2UkyIekyIfkjgCACAGIAVBiICogABqIgQqAgAiICARIA+UIBAgEpSTIg+TIhAgFiAX" +
"lCAVIBiUkiIRIBsgHJQgGiAdlJIiEpMiFZM4AgAgDSAOIBOSIg4gESASkiIRkzgCACAMICAgD5Ii" +
"DyAZIB6SIhKTOAIAIAsgFCAfkzgCACAKIBAgFZI4AgAgCSAOIBGSOAIAIAQgDyASkjgCACAFQQhq" +
"IgVB+P8BRw0ACwsCQEEAKAKMuNCDACIGQQFIDQBBACELQQAhDQNAAkACQCALQQN0IgVBgPjIgABq" +
"KAIAIgxFDQACQAJAIAxBAU4NAEMAAAAAIQ9DAAAAACEQQwAAAAAhEUMAAAAAIRIMAQtBACgCiLjQ" +
"gwBBA3QgBUGE+MiAAGooAgBBA3QiBWshBCANQQJ0IQlDAAAAACESIAwhCkMAAAAAIRFDAAAAACEQ" +
"QwAAAAAhDwNAIA8gCUGAuNCAAGoqAgAiDiAEQYSAqIAAaioCAJSSIQ8gECAOIARBgICogABqKgIA" +
"lJIhECARIA4gBUGEgKiAAGoqAgCUkiERIBIgDiAFQYCAqIAAaioCAJSSIRIgCUEEaiEJIARBeGoh" +
"BCAFQQhqIQUgCkF/aiIKDQALCyALQQR0IgVBjIi4gABqIBEgD5MiDiAOlCAQIBKSIg4gDpSSIhMg" +
"DyARkiIOIA6UIBAgEpMiDiAOlJIiDpJDAAAAP5SRIg9BACoCmLjQgwCUOAIAIAVBiIi4gABqIA6R" +
"QQAqApS40IMAIg6UkUMAgH9DlCIQQwCAf0MgEEMAgH9DXRs4AgAgBUGAiLiAAGogDiATkZSRQwCA" +
"f0OUIhBDAIB/QyAQQwCAf0NdGzgCACAFQYSIuIAAaiAPIA6UkUMAgH9DlCIOQwCAf0MgDkMAgH9D" +
"XRs4AgAgDCANaiENDAELIAtBBHQiBUGIiLiAAGpCADcDACAFQYCIuIAAakIANwMAQQAoAoy40IMA" +
"IQYLIAtBAWoiCyAGSA0ACwsCQCAGQQAoAoC40IMAIglGDQAgCUEBSA0AQYCIuIAAIQVBjIi4gAAh" +
"BCAJIQoDQCAEQXRqIAUqAgAgBUEQaioCAJJDAAAAP5Q4AgAgBEF4aiAFQQRqKgIAIAVBFGoqAgCS" +
"QwAAAD+UOAIAIARBfGogBUEIaioCACAFQRhqKgIAkkMAAAA/lDgCACAEIAVBDGoqAgAgBUEcaioC" +
"AJJDAAAAP5Q4AgAgBEEQaiEEIAVBIGohBSAKQX9qIgoNAAsLAkAgCUEBSA0AQYyIuIAAIQVBgIjH" +
"gAAhBANAIARDAACAPyAFKgIAQxe30TiSlTgCACAEQQRqIQQgBUEQaiEFIAlBf2oiCQ0ACwsL+QQI" +
"AX8CfQF/Cn0GfwF9AX8GfSAAEIqAgIAAIABBgMAAahCKgICAACAAQYCAAWoQioCAgAAgAEGAwAFq" +
"EIqAgIAAIABBhMABaiIBKgIAIQIgASAAKgIEIgMgAEGEwABqIgQqAgAiBZMiBiAAKgKAgAEiByAA" +
"KgKAwAEiCJMiCZI4AgAgACAAKgIAIgogACoCgEAiC5MiDCAAQYSAAWoiASoCACINIAKTIg6TOAKA" +
"wAEgASADIAWSIgMgDSACkiICkzgCACAAIAogC5IiBSAHIAiSIgeTOAKAgAEgBCAGIAmTOAIAIAAg" +
"DCAOkjgCgEAgACADIAKSOAIEIAAgBSAHkjgCAEEAIQEDQCAAIAFqIgRBjMABaiIPIARBDGoiECoC" +
"ACICIARBiMAAaiIRKgIAIgMgAUGM+JKAAGoqAgAiBZQgAUGI+JKAAGoqAgAiBiAEQYzAAGoiEioC" +
"ACIHlJIiCJMiCSABQYj4k4AAaioCACIKIARBiIABaiITKgIAIguUIAFBjPiTgABqKgIAIgwgBEGM" +
"gAFqIhQqAgAiDZSTIg4gAUGIuJOAAGoqAgAiFSAEQYjAAWoiFioCACIXlCABQYy4k4AAaioCACIY" +
"IA8qAgAiGZSTIhqTIhuSOAIAIBYgBEEIaiIEKgIAIhwgBiADlCAFIAeUkyIDkyIFIAsgDJQgCiAN" +
"lJIiBiAXIBiUIBUgGZSSIgeTIgqTOAIAIBQgAiAIkiICIAYgB5IiBpM4AgAgEyAcIAOSIgMgDiAa" +
"kiIHkzgCACASIAkgG5M4AgAgESAFIAqSOAIAIBAgAiAGkjgCACAEIAMgB5I4AgAgAUEIaiIBQfg/" +
"Rw0ACwv8BAgBfwJ9AX8KfQZ/AX0BfwZ9IAAQi4CAgAAgAEGAgAFqEIuAgIAAIABBgIACahCLgICA" +
"ACAAQYCAA2oQi4CAgAAgAEGEgANqIgEqAgAhAiABIAAqAgQiAyAAQYSAAWoiBCoCACIFkyIGIAAq" +
"AoCAAiIHIAAqAoCAAyIIkyIJkjgCACAAIAAqAgAiCiAAKgKAgAEiC5MiDCAAQYSAAmoiASoCACIN" +
"IAKTIg6TOAKAgAMgASADIAWSIgMgDSACkiICkzgCACAAIAogC5IiBSAHIAiSIgeTOAKAgAIgBCAG" +
"IAmTOAIAIAAgDCAOkjgCgIABIAAgAyACkjgCBCAAIAUgB5I4AgBBACEBA0AgACABaiIEQYyAA2oi" +
"DyAEQQxqIhAqAgAiAiAEQYiAAWoiESoCACIDIAFBjPiTgABqKgIAIgWUIAFBiPiTgABqKgIAIgYg" +
"BEGMgAFqIhIqAgAiB5SSIgiTIgkgAUGI+JWAAGoqAgAiCiAEQYiAAmoiEyoCACILlCABQYz4lYAA" +
"aioCACIMIARBjIACaiIUKgIAIg2UkyIOIAFBiPiUgABqKgIAIhUgBEGIgANqIhYqAgAiF5QgAUGM" +
"+JSAAGoqAgAiGCAPKgIAIhmUkyIakyIbkjgCACAWIARBCGoiBCoCACIcIAYgA5QgBSAHlJMiA5Mi" +
"BSALIAyUIAogDZSSIgYgFyAYlCAVIBmUkiIHkyIKkzgCACAUIAIgCJIiAiAGIAeSIgaTOAIAIBMg" +
"HCADkiIDIA4gGpIiB5M4AgAgEiAJIBuTOAIAIBEgBSAKkjgCACAQIAIgBpI4AgAgBCADIAeSOAIA" +
"IAFBCGoiAUH4/wBHDQALC+kECAF/An0Bfwp9Bn8BfQF/Bn0gABCQgICAACAAQYAQahCQgICAACAA" +
"QYAgahCQgICAACAAQYAwahCQgICAACAAQYQwaiIBKgIAIQIgASAAKgIEIgMgAEGEEGoiBCoCACIF" +
"kyIGIAAqAoAgIgcgACoCgDAiCJMiCZI4AgAgACAAKgIAIgogACoCgBAiC5MiDCAAQYQgaiIBKgIA" +
"Ig0gApMiDpM4AoAwIAEgAyAFkiIDIA0gApIiApM4AgAgACAKIAuSIgUgByAIkiIHkzgCgCAgBCAG" +
"IAmTOAIAIAAgDCAOkjgCgBAgACADIAKSOAIEIAAgBSAHkjgCAEEAIQEDQCAAIAFqIgRBjDBqIg8g" +
"BEEMaiIQKgIAIgIgBEGIEGoiESoCACIDIAFBjJiSgABqKgIAIgWUIAFBiJiSgABqKgIAIgYgBEGM" +
"EGoiEioCACIHlJIiCJMiCSABQYi4koAAaioCACIKIARBiCBqIhMqAgAiC5QgAUGMuJKAAGoqAgAi" +
"DCAEQYwgaiIUKgIAIg2UkyIOIAFBiKiSgABqKgIAIhUgBEGIMGoiFioCACIXlCABQYyokoAAaioC" +
"ACIYIA8qAgAiGZSTIhqTIhuSOAIAIBYgBEEIaiIEKgIAIhwgBiADlCAFIAeUkyIDkyIFIAsgDJQg" +
"CiANlJIiBiAXIBiUIBUgGZSSIgeTIgqTOAIAIBQgAiAIkiICIAYgB5IiBpM4AgAgEyAcIAOSIgMg" +
"DiAakiIHkzgCACASIAkgG5M4AgAgESAFIAqSOAIAIBAgAiAGkjgCACAEIAMgB5I4AgAgAUEIaiIB" +
"QfgPRw0ACwvxBAgBfwJ9AX8KfQZ/AX0BfwZ9IAAQkYCAgAAgAEGAIGoQkYCAgAAgAEGAwABqEJGA" +
"gIAAIABBgOAAahCRgICAACAAQYTgAGoiASoCACECIAEgACoCBCIDIABBhCBqIgQqAgAiBZMiBiAA" +
"KgKAQCIHIAAqAoBgIgiTIgmSOAIAIAAgACoCACIKIAAqAoAgIguTIgwgAEGEwABqIgEqAgAiDSAC" +
"kyIOkzgCgGAgASADIAWSIgMgDSACkiICkzgCACAAIAogC5IiBSAHIAiSIgeTOAKAQCAEIAYgCZM4" +
"AgAgACAMIA6SOAKAICAAIAMgApI4AgQgACAFIAeSOAIAQQAhAQNAIAAgAWoiBEGM4ABqIg8gBEEM" +
"aiIQKgIAIgIgBEGIIGoiESoCACIDIAFBjLiSgABqKgIAIgWUIAFBiLiSgABqKgIAIgYgBEGMIGoi" +
"EioCACIHlJIiCJMiCSABQYj4koAAaioCACIKIARBiMAAaiITKgIAIguUIAFBjPiSgABqKgIAIgwg" +
"BEGMwABqIhQqAgAiDZSTIg4gAUGI2JKAAGoqAgAiFSAEQYjgAGoiFioCACIXlCABQYzYkoAAaioC" +
"ACIYIA8qAgAiGZSTIhqTIhuSOAIAIBYgBEEIaiIEKgIAIhwgBiADlCAFIAeUkyIDkyIFIAsgDJQg" +
"CiANlJIiBiAXIBiUIBUgGZSSIgeTIgqTOAIAIBQgAiAIkiICIAYgB5IiBpM4AgAgEyAcIAOSIgMg" +
"DiAakiIHkzgCACASIAkgG5M4AgAgESAFIAqSOAIAIBAgAiAGkjgCACAEIAMgB5I4AgAgAUEIaiIB" +
"QfgfRw0ACwuTBQQBfwF9BH8CfQJAAkAgAEEASA0AQQAoAoS40IMAIgIgAEwNAEEAKAKAuNCDAEEB" +
"SA0BIAIgAGuyIAKylSEDQQAhAkEAIQBBACEEA0BBACEFQQAhBkEAIQcCQCACQYyIuIAAaioCACII" +
"IANfDQACQAJAIAggA5MgAEGAiMeAAGoqAgCUIgggAkGIiLiAAGoqAgCUIglDAACAT10gCUMAAAAA" +
"YHFFDQAgCakhBwwBC0EAIQcLAkACQCAIIAJBhIi4gABqKgIAlCIJQwAAgE9dIAlDAAAAAGBxRQ0A" +
"IAmpIQYMAQtBACEGCwJAIAggAkGAiLiAAGoqAgCUIghDAACAT10gCEMAAAAAYHFFDQAgCKkhBQwB" +
"C0EAIQULIABBg4iQgABqIAE6AAAgAEGCiJCAAGogBzoAACAAQYGIkIAAaiAGOgAAIABBgIiQgABq" +
"IAU6AAAgAkEQaiECIABBBGohACAEQQFqIgRBACgCgLjQgwBIDQAMAgsLQQAoAoC40IMAQQFIDQBB" +
"ACEAQQAhAkEAIQUDQCACQYCIuIAAaioCACEDIAJBhIi4gABqKgIAIQggAkGIiLiAAGoqAgAhCSAA" +
"QYOIkIAAaiABOgAAIABBgoiQgABqIQYCQAJAIAlDAACAT10gCUMAAAAAYHFFDQAgCakhBwwBC0EA" +
"IQcLIAYgBzoAACAAQYGIkIAAaiEGAkACQCAIQwAAgE9dIAhDAAAAAGBxRQ0AIAipIQcMAQtBACEH" +
"CyAGIAc6AAAgAEGAiJCAAGohBgJAAkAgA0MAAIBPXSADQwAAAABgcUUNACADqSEHDAELQQAhBwsg" +
"BiAHOgAAIABBBGohACACQRBqIQIgBUEBaiIFQQAoAoC40IMASA0ACwsLDQAgAEH/ARCMgICAAAtQ" +
"AEEAQwAAyEIgAUMAAIA/IAFDAACAP14bIAFDAADIQl4bOAKUuNCDAEEAQwAAyEIgAEMAAIA/IABD" +
"AACAP14bIABDAADIQl4bOAKYuNCDAAshAEEAIABBASAAQQFKGyIAQeAhIABB4CFIGzYChLjQgwAL" +
"6QQIAX8CfQF/Cn0GfwF9AX8GfSAAEJKAgIAAIABBgARqEJKAgIAAIABBgAhqEJKAgIAAIABBgAxq" +
"EJKAgIAAIABBhAxqIgEqAgAhAiABIAAqAgQiAyAAQYQEaiIEKgIAIgWTIgYgACoCgAgiByAAKgKA" +
"DCIIkyIJkjgCACAAIAAqAgAiCiAAKgKABCILkyIMIABBhAhqIgEqAgAiDSACkyIOkzgCgAwgASAD" +
"IAWSIgMgDSACkiICkzgCACAAIAogC5IiBSAHIAiSIgeTOAKACCAEIAYgCZM4AgAgACAMIA6SOAKA" +
"BCAAIAMgApI4AgQgACAFIAeSOAIAQQAhAQNAIAAgAWoiBEGMDGoiDyAEQQxqIhAqAgAiAiAEQYgE" +
"aiIRKgIAIgMgAUGMgJKAAGoqAgAiBZQgAUGIgJKAAGoqAgAiBiAEQYwEaiISKgIAIgeUkiIIkyIJ" +
"IAFBiIiSgABqKgIAIgogBEGICGoiEyoCACILlCABQYyIkoAAaioCACIMIARBjAhqIhQqAgAiDZST" +
"Ig4gAUGIhJKAAGoqAgAiFSAEQYgMaiIWKgIAIheUIAFBjISSgABqKgIAIhggDyoCACIZlJMiGpMi" +
"G5I4AgAgFiAEQQhqIgQqAgAiHCAGIAOUIAUgB5STIgOTIgUgCyAMlCAKIA2UkiIGIBcgGJQgFSAZ" +
"lJIiB5MiCpM4AgAgFCACIAiSIgIgBiAHkiIGkzgCACATIBwgA5IiAyAOIBqSIgeTOAIAIBIgCSAb" +
"kzgCACARIAUgCpI4AgAgECACIAaSOAIAIAQgAyAHkjgCACABQQhqIgFB+ANHDQALC+kECAF/An0B" +
"fwp9Bn8BfQF/Bn0gABCUgICAACAAQYAIahCUgICAACAAQYAQahCUgICAACAAQYAYahCUgICAACAA" +
"QYQYaiIBKgIAIQIgASAAKgIEIgMgAEGECGoiBCoCACIFkyIGIAAqAoAQIgcgACoCgBgiCJMiCZI4" +
"AgAgACAAKgIAIgogACoCgAgiC5MiDCAAQYQQaiIBKgIAIg0gApMiDpM4AoAYIAEgAyAFkiIDIA0g" +
"ApIiApM4AgAgACAKIAuSIgUgByAIkiIHkzgCgBAgBCAGIAmTOAIAIAAgDCAOkjgCgAggACADIAKS" +
"OAIEIAAgBSAHkjgCAEEAIQEDQCAAIAFqIgRBjBhqIg8gBEEMaiIQKgIAIgIgBEGICGoiESoCACID" +
"IAFBjIiSgABqKgIAIgWUIAFBiIiSgABqKgIAIgYgBEGMCGoiEioCACIHlJIiCJMiCSABQYiYkoAA" +
"aioCACIKIARBiBBqIhMqAgAiC5QgAUGMmJKAAGoqAgAiDCAEQYwQaiIUKgIAIg2UkyIOIAFBiJCS" +
"gABqKgIAIhUgBEGIGGoiFioCACIXlCABQYyQkoAAaioCACIYIA8qAgAiGZSTIhqTIhuSOAIAIBYg" +
"BEEIaiIEKgIAIhwgBiADlCAFIAeUkyIDkyIFIAsgDJQgCiANlJIiBiAXIBiUIBUgGZSSIgeTIgqT" +
"OAIAIBQgAiAIkiICIAYgB5IiBpM4AgAgEyAcIAOSIgMgDiAakiIHkzgCACASIAkgG5M4AgAgESAF" +
"IAqSOAIAIBAgAiAGkjgCACAEIAMgB5I4AgAgAUEIaiIBQfgHRw0ACwvpBAgBfwJ9AX8KfQZ/AX0B" +
"fwZ9IAAQk4CAgAAgAEGAAWoQk4CAgAAgAEGAAmoQk4CAgAAgAEGAA2oQk4CAgAAgAEGEA2oiASoC" +
"ACECIAEgACoCBCIDIABBhAFqIgQqAgAiBZMiBiAAKgKAAiIHIAAqAoADIgiTIgmSOAIAIAAgACoC" +
"ACIKIAAqAoABIguTIgwgAEGEAmoiASoCACINIAKTIg6TOAKAAyABIAMgBZIiAyANIAKSIgKTOAIA" +
"IAAgCiALkiIFIAcgCJIiB5M4AoACIAQgBiAJkzgCACAAIAwgDpI4AoABIAAgAyACkjgCBCAAIAUg" +
"B5I4AgBBACEBA0AgACABaiIEQYwDaiIPIARBDGoiECoCACICIARBiAFqIhEqAgAiAyABQYz6kYAA" +
"aioCACIFlCABQYj6kYAAaioCACIGIARBjAFqIhIqAgAiB5SSIgiTIgkgAUGI/JGAAGoqAgAiCiAE" +
"QYgCaiITKgIAIguUIAFBjPyRgABqKgIAIgwgBEGMAmoiFCoCACINlJMiDiABQYj7kYAAaioCACIV" +
"IARBiANqIhYqAgAiF5QgAUGM+5GAAGoqAgAiGCAPKgIAIhmUkyIakyIbkjgCACAWIARBCGoiBCoC" +
"ACIcIAYgA5QgBSAHlJMiA5MiBSALIAyUIAogDZSSIgYgFyAYlCAVIBmUkiIHkyIKkzgCACAUIAIg" +
"CJIiAiAGIAeSIgaTOAIAIBMgHCADkiIDIA4gGpIiB5M4AgAgEiAJIBuTOAIAIBEgBSAKkjgCACAQ" +
"IAIgBpI4AgAgBCADIAeSOAIAIAFBCGoiAUH4AEcNAAsL4QkOBn0BfwF9AX8EfQF/AX0BfwJ9AX8D" +
"fQF/A30DfyAAIAAqAgAiASAAKgIIIgKSIgMgACoCECIEIAAqAhgiBZIiBpM4AhAgACADIAaSIgM4" +
"AgAgAEEcaiIHKgIAIQYgByAAKgIEIgggAEEMaiIJKgIAIgqTIgsgBCAFkyIEkjgCACAAIAEgApMi" +
"ASAAQRRqIgcqAgAiAiAGkyIFkzgCGCAHIAggCpIiCCACIAaSIgaTOAIAIAkgCyAEkzgCACAAIAEg" +
"BZI4AgggACAIIAaSIgY4AgQgACAAKgIgIgUgACoCKCIIkiIKIAAqAjAiCyAAKgI4IgySIg2SIgE4" +
"AiAgAEE0aiIJKgIAIQIgAEE8aiIOKgIAIQQgDiAAQSRqIgcqAgAiDyAAQSxqIhAqAgAiEZMiEiAL" +
"IAyTIguSOAIAIAAgBSAIkyIFIAIgBJMiCJM4AjggCSAPIBGSIgwgAiAEkiICkzgCACAAIAogDZM4" +
"AjAgECASIAuTOAIAIAAgBSAIkjgCKCAHIAwgApIiAjgCACAAQdwAaiIJKgIAIQQgAEHUAGoiDioC" +
"ACEFIAAqAkghCCAAKgJAIQogCSAAQcQAaiIQKgIAIgsgAEHMAGoiEyoCACIMkyINIAAqAlAiDyAA" +
"KgJYIhGTIhKSOAIAIAAgCiAIkyIUIAUgBJMiFZM4AlggDiALIAySIgsgBSAEkiIMkzgCACAAIAog" +
"CJIiFiAPIBGSIg+TOAJQIBMgDSASkzgCACAAIBQgFZI4AkggAEH8AGoiCSoCACEEIABB9ABqIg4q" +
"AgAhBSAAKgJoIQggACoCYCEKIAkgAEHkAGoiEyoCACINIABB7ABqIhcqAgAiEZMiEiAAKgJwIhQg" +
"ACoCeCIVkyIYkjgCACAAIAogCJMiGSAFIASTIhqTOAJ4IA4gDSARkiINIAUgBJIiBJM4AgAgACAK" +
"IAiSIgUgFCAVkiIIkzgCcCAXIBIgGJM4AgAgACAZIBqSOAJoIBMgBiACkyIKIBYgD5IiDyAFIAiS" +
"IgWTIgiSOAIAIAAgAyABkyIRIAsgDJIiCyANIASSIgSTIgyTOAJgIBAgBiACkiIGIAsgBJIiApM4" +
"AgAgACADIAGSIgMgDyAFkiIBkzgCQCAHIAogCJM4AgAgACARIAySOAIgIAAgBiACkjgCBCAAIAMg" +
"AZI4AgBBACEHA0AgACAHaiIJQewAaiIOIAlBDGoiECoCACIDIAlBKGoiEyoCACIGIAdBzPiRgABq" +
"KgIAIgGUIAdByPiRgABqKgIAIgIgCUEsaiIXKgIAIgSUkiIFkyIIIAdBiPmRgABqKgIAIgogCUHI" +
"AGoiGyoCACILlCAHQYz5kYAAaioCACIMIAlBzABqIhwqAgAiDZSTIg8gB0Ho+JGAAGoqAgAiESAJ" +
"QegAaiIdKgIAIhKUIAdB7PiRgABqKgIAIhQgDioCACIVlJMiFpMiGJI4AgAgHSAJQQhqIgkqAgAi" +
"GSACIAaUIAEgBJSTIgaTIgEgCyAMlCAKIA2UkiICIBIgFJQgESAVlJIiBJMiCpM4AgAgHCADIAWS" +
"IgMgAiAEkiICkzgCACAbIBkgBpIiBiAPIBaSIgSTOAIAIBcgCCAYkzgCACATIAEgCpI4AgAgECAD" +
"IAKSOAIAIAkgBiAEkjgCACAHQQhqIgdBGEcNAAsL6QQIAX8CfQF/Cn0GfwF9AX8GfSAAEJWAgIAA" +
"IABBgAJqEJWAgIAAIABBgARqEJWAgIAAIABBgAZqEJWAgIAAIABBhAZqIgEqAgAhAiABIAAqAgQi" +
"AyAAQYQCaiIEKgIAIgWTIgYgACoCgAQiByAAKgKABiIIkyIJkjgCACAAIAAqAgAiCiAAKgKAAiIL" +
"kyIMIABBhARqIgEqAgAiDSACkyIOkzgCgAYgASADIAWSIgMgDSACkiICkzgCACAAIAogC5IiBSAH" +
"IAiSIgeTOAKABCAEIAYgCZM4AgAgACAMIA6SOAKAAiAAIAMgApI4AgQgACAFIAeSOAIAQQAhAQNA" +
"IAAgAWoiBEGMBmoiDyAEQQxqIhAqAgAiAiAEQYgCaiIRKgIAIgMgAUGM/JGAAGoqAgAiBZQgAUGI" +
"/JGAAGoqAgAiBiAEQYwCaiISKgIAIgeUkiIIkyIJIAFBiICSgABqKgIAIgogBEGIBGoiEyoCACIL" +
"lCABQYyAkoAAaioCACIMIARBjARqIhQqAgAiDZSTIg4gAUGI/pGAAGoqAgAiFSAEQYgGaiIWKgIA" +
"IheUIAFBjP6RgABqKgIAIhggDyoCACIZlJMiGpMiG5I4AgAgFiAEQQhqIgQqAgAiHCAGIAOUIAUg" +
"B5STIgOTIgUgCyAMlCAKIA2UkiIGIBcgGJQgFSAZlJIiB5MiCpM4AgAgFCACIAiSIgIgBiAHkiIG" +
"kzgCACATIBwgA5IiAyAOIBqSIgeTOAIAIBIgCSAbkzgCACARIAUgCpI4AgAgECACIAaSOAIAIAQg" +
"AyAHkjgCACABQQhqIgFB+AFHDQALC+YECAF/An0Bfwp9Bn8BfQF/Bn0gABCWgICAACAAQcAAahCW" +
"gICAACAAQYABahCWgICAACAAQcABahCWgICAACAAQcQBaiIBKgIAIQIgASAAKgIEIgMgAEHEAGoi" +
"BCoCACIFkyIGIAAqAoABIgcgACoCwAEiCJMiCZI4AgAgACAAKgIAIgogACoCQCILkyIMIABBhAFq" +
"IgEqAgAiDSACkyIOkzgCwAEgASADIAWSIgMgDSACkiICkzgCACAAIAogC5IiBSAHIAiSIgeTOAKA" +
"ASAEIAYgCZM4AgAgACAMIA6SOAJAIAAgAyACkjgCBCAAIAUgB5I4AgBBACEBA0AgACABaiIEQcwB" +
"aiIPIARBDGoiECoCACICIARByABqIhEqAgAiAyABQYz5kYAAaioCACIFlCABQYj5kYAAaioCACIG" +
"IARBzABqIhIqAgAiB5SSIgiTIgkgAUGI+pGAAGoqAgAiCiAEQYgBaiITKgIAIguUIAFBjPqRgABq" +
"KgIAIgwgBEGMAWoiFCoCACINlJMiDiABQcj5kYAAaioCACIVIARByAFqIhYqAgAiF5QgAUHM+ZGA" +
"AGoqAgAiGCAPKgIAIhmUkyIakyIbkjgCACAWIARBCGoiBCoCACIcIAYgA5QgBSAHlJMiA5MiBSAL" +
"IAyUIAogDZSSIgYgFyAYlCAVIBmUkiIHkyIKkzgCACAUIAIgCJIiAiAGIAeSIgaTOAIAIBMgHCAD" +
"kiIDIA4gGpIiB5M4AgAgEiAJIBuTOAIAIBEgBSAKkjgCACAQIAIgBpI4AgAgBCADIAeSOAIAIAFB" +
"CGoiAUE4Rw0ACwvRBAsDfQF/DX0BfwF9AX8BfQF/AX0BfwN9IAAgACoCACIBIAAqAggiApMiAzgC" +
"CCAAQQxqIgQgACoCBCIFIAQqAgAiBpMiBzgCACAAIAEgApIiASAAKgIQIgIgACoCGCIIkiIJkiIK" +
"IAAqAiAiCyAAKgIoIgySIg0gACoCMCIOIAAqAjgiD5IiEJIiEZI4AgAgACAKIBGTOAIgIABBFGoi" +
"EiAFIAaSIgUgEioCACIGIABBHGoiEioCACIKkiIRkyITIA0gEJMiDZM4AgAgAEEkaiIUIAUgEZIi" +
"BSAUKgIAIhAgAEEsaiIUKgIAIhGSIhUgAEE0aiIWKgIAIhcgAEE8aiIYKgIAIhmSIhqSIhuTOAIA" +
"IAAgASAJkyIBIBUgGpMiCZM4AjAgFiATIA2SOAIAIAAgASAJkjgCECAAIAUgG5I4AgQgGCAHIAIg" +
"CJMiAUEAKgKs+JGAACIClEEAKgKo+JGAACIFIAYgCpMiBpSSIgiTIglBACoCyPiRgAAiCiALIAyT" +
"IguUQQAqAsz4kYAAIgwgECARkyINlJMiEEEAKgK4+JGAACIRIA4gD5MiDpRBACoCvPiRgAAiDyAX" +
"IBmTIhOUkyIVkyIXkjgCACAAIAMgBSABlCACIAaUkyIBkyICIAsgDJQgCiANlJIiBSAOIA+UIBEg" +
"E5SSIgaTIgqTOAI4IBQgByAIkiIHIAUgBpIiBZM4AgAgACADIAGSIgMgECAVkiIBkzgCKCASIAkg" +
"F5M4AgAgACACIAqSOAIYIAQgByAFkjgCACAAIAMgAZI4AggLAKQCBG5hbWUBnAIXAANsb2cBA2Nv" +
"cwIDc2luAwNleHAED2dldF9pbnB1dF9hcnJheQUQZ2V0X291dHB1dF9hcnJheQYEaW5pdAcEY2Fs" +
"YwgNZmZ0X2NhbGNfNDA5NgkNZmZ0X2NhbGNfODE5MgoNZmZ0X2NhbGNfMTAyNAsNZmZ0X2NhbGNf" +
"MjA0OAwRcmVuZGVyX2xpbmVfYWxwaGENEnJlbmRlcl9saW5lX29wYXF1ZQ4Kc2V0X3ZvbHVtZQ8K" +
"c2V0X2hlaWdodBAMZmZ0X2NhbGNfMjU2EQxmZnRfY2FsY181MTISC2ZmdF9jYWxjXzY0EwtmZnRf" +
"Y2FsY18xNhQMZmZ0X2NhbGNfMTI4FQtmZnRfY2FsY18zMhYKZmZ0X2NhbGNfOAA9CXByb2R1Y2Vy" +
"cwEMcHJvY2Vzc2VkLWJ5AQVjbGFuZx0xMC4wLjAgKEZlZG9yYSAxMC4wLjAtMS5mYzMyKQ==";

    let decode64 = function(b64) {
        var str = atob(b64);
        var buf = new Uint8Array(str.length);
        for (var k = 0; k < str.length; k++)
            buf[k] = str.charCodeAt(k);
        return buf;
    }

    let wasm_module_promise = WebAssembly.compile(decode64(wasm_embedded_base64));
    let wasm_imports = {
        env: {
            cos: Math.cos,
            sin: Math.sin,
            log: Math.log,
            exp: Math.exp
        }
    };

    var ShowCQT = {
        instantiate: async function() {
            var instance = await WebAssembly.instantiate(await wasm_module_promise, wasm_imports);
            var exports = instance.exports;
            var buffer = exports.memory.buffer;
            return {
                fft_size: 0,
                width: 0,
                init: function(rate, width, height, bar_v, sono_v, supersampling) {
                    this.width = width;
                    this.fft_size = exports.init(rate, width, height, bar_v, sono_v, supersampling);
                    if (!this.fft_size)
                        throw new Error("ShowCQT init: cannot initialize ShowCQT");
                    this.inputs = [
                        new Float32Array(buffer, exports.get_input_array(0), this.fft_size),
                        new Float32Array(buffer, exports.get_input_array(1), this.fft_size)
                    ];
                    this.output = new Uint8ClampedArray(buffer, exports.get_output_array(), this.width * 4);
                },
                calc: exports.calc,
                render_line_alpha: exports.render_line_alpha,
                render_line_opaque: exports.render_line_opaque,
                set_volume: exports.set_volume,
                set_height: exports.set_height
            }
        }
    };
}
